# frozen_string_literal: true

module SolidScore
  module Formatters
    class HtmlFormatter < BaseFormatter
      def format(results)
        return empty_html if results.empty?

        build_html(results)
      end

      private

      def empty_html
        build_page("No classes found to analyze.", "")
      end

      def build_html(results)
        summary = build_summary(results)
        chart = build_chart(results)
        table = build_table(results)

        build_page(summary + chart, table)
      end

      def build_page(header_content, body_content)
        <<~HTML
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>solid-score Report</title>
            <style>#{css}</style>
          </head>
          <body>
            <div class="container">
              <h1>solid-score Report <span class="version">v#{VERSION}</span></h1>
              #{header_content}
              #{body_content}
              <footer>Generated by solid-score v#{VERSION}</footer>
            </div>
          </body>
          </html>
        HTML
      end

      def build_summary(results)
        avg_total = (results.sum(&:total) / results.size).round(1)
        avgs = %i[srp ocp lsp isp dip].map do |p|
          [p, (results.sum(&p) / results.size).round(1)]
        end.to_h

        <<~HTML
          <div class="summary">
            <div class="summary-card summary-total">
              <div class="summary-label">Average Score</div>
              <div class="summary-value #{score_color_class(avg_total)}">#{avg_total}</div>
            </div>
            <div class="summary-card">
              <div class="summary-label">Classes Analyzed</div>
              <div class="summary-value">#{results.size}</div>
            </div>
            #{avgs.map { |p, v| principle_card(p, v) }.join}
          </div>
        HTML
      end

      def principle_card(principle, value)
        <<~HTML
          <div class="summary-card">
            <div class="summary-label">#{principle.to_s.upcase}</div>
            <div class="summary-value #{score_color_class(value)}">#{value}</div>
          </div>
        HTML
      end

      def build_chart(results)
        avgs = %i[srp ocp lsp isp dip].map do |p|
          [p.to_s.upcase, (results.sum(&p) / results.size).round(1)]
        end

        bar_height = 32
        gap = 8
        chart_height = avgs.size * (bar_height + gap) + 20
        label_width = 40
        chart_width = 500

        bars = avgs.each_with_index.map do |(label, value), i|
          y = i * (bar_height + gap) + 10
          bar_w = [(value / 100.0 * (chart_width - label_width - 60)).round(1), 0].max
          color = score_hex_color(value)

          <<~SVG
            <text x="#{label_width - 5}" y="#{y + bar_height / 2 + 5}" text-anchor="end" class="chart-label">#{label}</text>
            <rect x="#{label_width}" y="#{y}" width="#{bar_w}" height="#{bar_height}" rx="4" fill="#{color}" />
            <text x="#{label_width + bar_w + 5}" y="#{y + bar_height / 2 + 5}" class="chart-value">#{value}</text>
          SVG
        end.join

        <<~HTML
          <div class="chart-container">
            <h2>Score Overview</h2>
            <svg width="#{chart_width}" height="#{chart_height}" class="chart">
              #{bars}
            </svg>
          </div>
        HTML
      end

      def build_table(results)
        rows = results.sort_by(&:total).map { |r| table_row(r) }.join

        <<~HTML
          <h2>Details (#{results.size} classes)</h2>
          <div class="table-wrapper">
            <table>
              <thead>
                <tr>
                  <th>Class</th>
                  <th>File</th>
                  <th>SRP</th>
                  <th>OCP</th>
                  <th>LSP</th>
                  <th>ISP</th>
                  <th>DIP</th>
                  <th>Total</th>
                </tr>
              </thead>
              <tbody>
                #{rows}
              </tbody>
            </table>
          </div>
        HTML
      end

      def table_row(result)
        <<~HTML
          <tr>
            <td class="class-name">#{escape_html(result.class_name)}</td>
            <td class="file-path">#{escape_html(result.file_path)}</td>
            #{score_cell(result.srp)}
            #{score_cell(result.ocp)}
            #{score_cell(result.lsp)}
            #{score_cell(result.isp)}
            #{score_cell(result.dip)}
            #{score_cell(result.total.round(1))}
          </tr>
        HTML
      end

      def score_cell(value)
        %(<td class="score #{score_color_class(value)}">#{value}</td>)
      end

      def score_color_class(score)
        if score >= 80
          "score-green"
        elsif score >= 50
          "score-yellow"
        else
          "score-red"
        end
      end

      def score_hex_color(score)
        if score >= 80
          "#22c55e"
        elsif score >= 50
          "#eab308"
        else
          "#ef4444"
        end
      end

      def escape_html(text)
        text.to_s
            .gsub("&", "&amp;")
            .gsub("<", "&lt;")
            .gsub(">", "&gt;")
            .gsub('"', "&quot;")
      end

      def css
        <<~CSS
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #f8fafc; color: #1e293b; line-height: 1.6; }
          .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
          h1 { font-size: 1.5rem; margin-bottom: 1.5rem; }
          h1 .version { font-weight: normal; color: #64748b; font-size: 0.875rem; }
          h2 { font-size: 1.125rem; margin: 1.5rem 0 0.75rem; }

          .summary { display: flex; flex-wrap: wrap; gap: 0.75rem; margin-bottom: 1.5rem; }
          .summary-card { background: #fff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 0.75rem 1rem; min-width: 100px; text-align: center; }
          .summary-total { border-width: 2px; }
          .summary-label { font-size: 0.75rem; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; }
          .summary-value { font-size: 1.5rem; font-weight: 700; }

          .chart-container { background: #fff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 1rem; margin-bottom: 1.5rem; }
          .chart-label { font-size: 13px; fill: #475569; font-family: inherit; }
          .chart-value { font-size: 13px; fill: #475569; font-family: inherit; }

          .table-wrapper { overflow-x: auto; }
          table { width: 100%; border-collapse: collapse; background: #fff; border: 1px solid #e2e8f0; border-radius: 8px; font-size: 0.875rem; }
          thead { background: #f1f5f9; }
          th { padding: 0.625rem 0.75rem; text-align: left; font-weight: 600; border-bottom: 2px solid #e2e8f0; }
          td { padding: 0.5rem 0.75rem; border-bottom: 1px solid #f1f5f9; }
          tr:hover { background: #f8fafc; }
          .class-name { font-weight: 500; white-space: nowrap; }
          .file-path { color: #64748b; font-size: 0.8rem; max-width: 300px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
          .score { text-align: right; font-variant-numeric: tabular-nums; font-weight: 500; }

          .score-green { color: #16a34a; }
          .score-yellow { color: #ca8a04; }
          .score-red { color: #dc2626; }

          footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 0.75rem; text-align: center; }
        CSS
      end
    end
  end
end
