#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"

MAX_ROWS = 30

input = STDIN.read.strip
data = JSON.parse(input)

classes = data["classes"] || []
summary = data["summary"] || {}
version = data["version"] || "unknown"

avg_score = summary["average_score"] || 0.0
total_classes = summary["total_classes"] || 0

def score_emoji(score)
  if score >= 80
    "\u{1f7e2}" # green circle
  elsif score >= 50
    "\u{1f7e1}" # yellow circle
  else
    "\u{1f534}" # red circle
  end
end

lines = []
lines << "<!-- solid-score-report -->"
lines << "## #{score_emoji(avg_score)} solid-score Report"
lines << ""

if classes.empty?
  lines << "No classes found to analyze."
else
  lines << "| Class | SRP | OCP | LSP | ISP | DIP | Total |"
  lines << "|-------|-----|-----|-----|-----|-----|-------|"

  sorted = classes.sort_by { |c| c["total"] }
  display = sorted.first(MAX_ROWS)

  display.each do |c|
    total = c["total"]
    lines << "| #{c['class_name']} | #{c['srp']} | #{c['ocp']} | #{c['lsp']} | #{c['isp']} | #{c['dip']} | #{score_emoji(total)} #{total} |"
  end

  if sorted.size > MAX_ROWS
    lines << ""
    lines << "*...and #{sorted.size - MAX_ROWS} more classes*"
  end

  lines << ""
  lines << "**Average: #{avg_score}** | Classes: #{total_classes}"
end

lines << ""
lines << "<sub>Generated by solid-score v#{version}</sub>"

puts lines.join("\n")
